on: push
jobs: 
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build and test
        run: dotnet test --collect:"OpenCover"
      - name: Generate code coverage report
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        run: reportgenerator "-reports:coverage.opencover.xml" "-targetdir:coveragereport"